In [2]:
import pandas as pd
from datetime import date
import numpy as np

df = pd.read_csv("data/raw/Sample - Superstore.csv", encoding="cp1252", dtype={"Postal Code": "str"})
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%m/%d/%Y").dt.normalize()
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%m/%d/%Y").dt.normalize()

federal_holidays = np.array([

    # 2014
    "2014-01-01", "2014-01-20", "2014-02-17",
    "2014-05-26", "2014-07-04", "2014-09-01",
    "2014-10-13", "2014-11-11", "2014-11-27", "2014-12-25",

    # 2015
    "2015-01-01", "2015-01-19", "2015-02-16",
    "2015-05-25", "2015-07-03", "2015-09-07",
    "2015-10-12", "2015-11-11", "2015-11-26", "2015-12-25",

    # 2016
    "2016-01-01", "2016-01-18", "2016-02-15",
    "2016-05-30", "2016-07-04", "2016-09-05",
    "2016-10-10", "2016-11-11", "2016-11-24", "2016-12-26",

    # 2017
    "2017-01-02", "2017-01-16", "2017-02-20",
    "2017-05-29", "2017-07-04", "2017-09-04",
    "2017-10-09", "2017-11-10", "2017-11-23", "2017-12-25",

    # Needed because the dataset includes shipments in early 2018
    "2018-01-01",

], dtype="datetime64[D]")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   str
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(2), str(14)
memory usage: 1.6 MB

In [4]:
df.shape

(9994, 21)

In [5]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355,2016-05-03 23:06:58.571142,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,623.245101,2.225110,0.206452,234.260108

In [6]:
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [8]:
df["Ship Mode"].value_counts()
df[df["Ship Mode"] == "Same Day"].describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,543.000000,543,543,543.000000,543.000000,543.000000,543.000000
mean,5128.909761,2016-06-07 18:04:38.453038,2016-06-07 19:08:17.237569,236.396179,3.609576,0.152394,29.266591
min,367.000000,2014-02-18 00:00:00,2014-02-18 00:00:00,0.556000,1.000000,0.000000,-3839.990400
25%,2866.500000,2015-09-15 00:00:00,2015-09-15 00:00:00,16.615000,2.000000,0.000000,2.156700
50%,5125.000000,2016-07-04 00:00:00,2016-07-04 00:00:00,55.176000,3.000000,0.200000,8.027000
75%,7329.500000,2017-06-07 00:00:00,2017-06-07 00:00:00,209.793000,5.000000,0.200000,29.563500
max,9964.000000,2017-12-27 00:00:00,2017-12-27 00:00:00,7999.980000,14.000000,0.800000,2229.024000
std,2696.357615,NaN,NaN,555.258791,2.129233,0.198365,226.689497

In [9]:
#df["Business Days to Ship"] = np.busday_count(df["Order Date"].values.astype("datetime64[D]"), df["Ship Date"].values.astype("datetime64[D]"))
#df = df.drop(columns="Business Days to Ship")
df.insert(4, "Business Days to Ship", 
          np.busday_count(df["Order Date"].values.astype("datetime64[D]"), 
                          df["Ship Date"].values.astype("datetime64[D]"),
                          holidays=federal_holidays))
df[df["Ship Mode"] == "Standard Class"].describe()

,Row ID,Order Date,Ship Date,Business Days to Ship,Sales,Quantity,Discount,Profit
count,5968.000000,5968,5968,5968.000000,5968.000000,5968.000000,5968.000000,5968.000000
mean,5036.776977,2016-04-17 02:17:17.533512,2016-04-22 02:26:42.144772,3.420912,227.583067,3.819873,0.160023,27.494770
min,4.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2597.750000,2015-04-28 00:00:00,2015-05-04 00:00:00,3.000000,16.779000,2.000000,0.000000,1.467200
50%,5060.500000,2016-06-05 00:00:00,2016-06-09 00:00:00,4.000000,52.768000,3.000000,0.200000,8.301000
75%,7495.250000,2017-05-03 00:00:00,2017-05-07 06:00:00,4.000000,209.947500,5.000000,0.200000,28.765800
max,9993.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,5.000000,22638.480000,14.000000,0.800000,8399.976000
std,2858.286252,NaN,NaN,1.101416,646.738998,2.246699,0.210782,250.010543

In [10]:
df[df["Ship Mode"] == "First Class"].describe()

,Row ID,Order Date,Ship Date,Business Days to Ship,Sales,Quantity,Discount,Profit
count,1538.000000,1538,1538,1538.000000,1538.000000,1538.000000,1538.000000,1538.000000
mean,4875.510403,2016-05-31 05:25:49.544863,2016-06-02 09:48:55.240572,1.364759,228.497024,3.701560,0.164610,31.839948
min,36.000000,2014-01-06 00:00:00,2014-01-07 00:00:00,0.000000,0.984000,1.000000,0.000000,-2639.991200
25%,2058.250000,2015-06-16 12:00:00,2015-06-19 06:00:00,1.000000,18.164000,2.000000,0.000000,1.791450
50%,4898.500000,2016-08-30 00:00:00,2016-09-01 00:00:00,1.000000,54.940000,3.000000,0.200000,8.778900
75%,7617.750000,2017-06-10 00:00:00,2017-06-12 00:00:00,2.000000,199.980000,5.000000,0.200000,28.831950
max,9982.000000,2017-12-29 00:00:00,2017-12-31 00:00:00,3.000000,13999.960000,14.000000,0.800000,6719.980800
std,2989.939571,NaN,NaN,0.850722,630.384710,2.119098,0.210319,257.794233

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Row ID                 9994 non-null   int64
 1   Order ID               9994 non-null   str
 2   Order Date             9994 non-null   datetime64[us]
 3   Ship Date              9994 non-null   datetime64[us]
 4   Business Days to Ship  9994 non-null   int64
 5   Ship Mode              9994 non-null   str
 6   Customer ID            9994 non-null   str
 7   Customer Name          9994 non-null   str
 8   Segment                9994 non-null   str
 9   Country                9994 non-null   str
 10  City                   9994 non-null   str
 11  State                  9994 non-null   str
 12  Postal Code            9994 non-null   str
 13  Region                 9994 non-null   str
 14  Product ID             9994 non-null   str
 15  Category               9994 non-null   str
 16  Sub-Category           9994 non-null   str
 17  Product Name           9994 non-null   str
 18  Sales                  9994 non-null   float64
 19  Quantity               9994 non-null   int64
 20  Discount               9994 non-null   float64
 21  Profit                 9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(14)
memory usage: 1.7 MB

In [12]:
df["Order ID"].nunique()

5009

In [13]:
df["Ship Mode"].unique()

<StringArray>
['Second Class', 'Standard Class', 'First Class', 'Same Day']
Length: 4, dtype: str

In [14]:
df["Row ID"].is_unique
df["Row ID"].unique()

array([   1,    2,    3, ..., 9992, 9993, 9994], shape=(9994,))

In [15]:
df["Order ID"].nunique()

5009

In [16]:
df.groupby("Order ID")["Ship Date"].nunique(dropna=False).sort_values(ascending=False)

Order ID
CA-2014-100006    1
CA-2014-100090    1
CA-2014-100293    1
CA-2014-100328    1
CA-2014-100363    1
                 ..
US-2017-168802    1
US-2017-169320    1
US-2017-169488    1
US-2017-169502    1
US-2017-169551    1
Name: Ship Date, Length: 5009, dtype: int64

In [17]:
order_fields = ["Order Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Country",
    "City",
    "State",
    "Postal Code",
    "Region",]

order_variation = df.groupby("Order ID")[order_fields].nunique(dropna=False)

inconsistent_order = order_variation[order_variation.gt(1).any(axis=1)]

inconsistent_order

Empty DataFrame
Columns: [Order Date, Ship Date, Ship Mode, Customer ID, Country, City, State, Postal Code, Region]
Index: []

In [18]:
df.isna().sum().sum() == 0

np.True_

In [19]:
df[df["Profit"] < 0][["Order ID","Order Date","Ship Date","Ship Mode","Sales","Profit"]].sort_values("Profit").head(10)

,Order ID,Order Date,Ship Date,Ship Mode,Sales,Profit
7772,CA-2016-108196,2016-11-25,2016-12-02,Standard Class,4499.985,-6599.9780
683,US-2017-168116,2017-11-04,2017-11-04,Same Day,7999.980,-3839.9904
9774,CA-2014-169019,2014-07-26,2014-07-30,Standard Class,2177.584,-3701.8928
3011,CA-2017-134845,2017-04-17,2017-04-23,Standard Class,2549.985,-3399.9800
4991,US-2017-122714,2017-12-07,2017-12-13,Standard Class,1889.990,-2929.4845
3151,CA-2015-147830,2015-12-15,2015-12-18,First Class,1799.994,-2639.9912
5310,CA-2017-131254,2017-11-19,2017-11-21,First Class,1525.188,-2287.7820
9639,CA-2015-116638,2015-01-28,2015-01-31,Second Class,4297.644,-1862.3124
1199,CA-2016-130946,2016-04-08,2016-04-12,Standard Class,1088.792,-1850.9464
2697,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,22638.480,-1811.0784

In [20]:
df.loc[df["Ship Mode"] == "Same Day",["Order ID", "Order Date", "Ship Date", "Ship Mode"]].head(10)

           Order ID Order Date  Ship Date Ship Mode
366  CA-2016-155516 2016-10-21 2016-10-21  Same Day
367  CA-2016-155516 2016-10-21 2016-10-21  Same Day
368  CA-2016-155516 2016-10-21 2016-10-21  Same Day
369  CA-2016-155516 2016-10-21 2016-10-21  Same Day
657  US-2016-156097 2016-09-19 2016-09-19  Same Day
658  US-2016-156097 2016-09-19 2016-09-19  Same Day
664  CA-2016-143308 2016-11-04 2016-11-04  Same Day
683  US-2017-168116 2017-11-04 2017-11-04  Same Day
684  US-2017-168116 2017-11-04 2017-11-04  Same Day
746  CA-2014-124429 2014-05-27 2014-05-27  Same Day

In [21]:
df.groupby("Ship Mode").size().reset_index(name="line_count")

        Ship Mode  line_count
0     First Class        1538
1        Same Day         543
2    Second Class        1945
3  Standard Class        5968

In [22]:
df.groupby("Ship Mode")["Profit"].mean().round(2).reset_index(name="Average Profit")

        Ship Mode  Average Profit
0     First Class           31.84
1        Same Day           29.27
2    Second Class           29.54
3  Standard Class           27.49

In [23]:
df.groupby("Ship Mode").agg(
 #   "Total Sales" = ("Sales", "sum"),
    Total_Sales = ("Sales", "sum"),
    avg_profit = ("Profit", "mean"),
    largest_sale = ("Sales", "max")
)

                 Total_Sales  avg_profit  largest_sale
Ship Mode
First Class     3.514284e+05   31.839948      13999.96
Same Day        1.283631e+05   29.266591       7999.98
Second Class    4.591936e+05   29.535545       8749.95
Standard Class  1.358216e+06   27.494770      22638.48

In [24]:
df.groupby(["Region", "Category"]).agg(
    avg_sales=("Sales", "mean"),
    tot_profit=("Profit", "sum"),
    order_count=("Order ID", "nunique")
).reset_index()

     Region         Category   avg_sales  tot_profit  order_count
0   Central        Furniture  340.534644  -2871.0494          403
1   Central  Office Supplies  117.458801   8879.9799          880
2   Central       Technology  405.753124  33697.4320          356
3      East        Furniture  346.574383   3046.1658          488
4      East  Office Supplies  120.044425  41014.5791         1074
5      East       Technology  495.278469  47462.0351          443
6     South        Furniture  353.309289   6771.2061          278
7     South  Office Supplies  126.282727  19986.3928          619
8     South       Technology  507.753952  19991.8314          255
9      West        Furniture  357.302325  11504.9503          595
10     West  Office Supplies  116.422377  52609.8490         1169
11     West       Technology  420.687533  44303.6496          490

In [25]:
(
    df[df["Profit"] > 0]       # WHERE
      .groupby("Ship Mode")    # GROUP BY
      .agg(                    # SELECT aggregates
          sales=("Sales", "sum"),
          orders=("Order ID", "nunique"),
      )
      .reset_index()
      .sort_values("sales", ascending=False)  # ORDER BY
)

        Ship Mode         sales  orders
3  Standard Class  1.042033e+06    2622
2    Second Class  3.747976e+05     856
0     First Class  2.841382e+05     702
1        Same Day  9.983832e+04     227